name: Build Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.18'
          architecture: 'x64'
          cache: 'pip'

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade pyinstaller rarfile py7zr

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "VAE" --strip --clean --optimize "2" --add-data "Src/extract_addons.py:." --add-data "Src/extract_archives.py:." --add-data "Src/Bin:Bin/"  "Src/cli.py"

      - name: Move Bin and Remove Gmad Windows/macOS
        run: |
          mv dist/VAE/_internal/Bin dist/VAE/Bin
          rm -f dist/VAE/Bin/Windows/gmad.exe
          rm -f dist/VAE/Bin/Darwin/gmad_osx

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VAE-Development-Ubuntu
          path: dist/VAE
