name: Build Windows

on:
  push:
    branches:
      - beta
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.3
        with:
          length: 7

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10.11'
          architecture: 'x64'
          cache: 'pip'

      - name: Create virtual environment
        run: py -m venv .venv

      - name: Activate virtual environment
        run: .venv\Scripts\activate

      - name: Install dependencies
        run: pip install --upgrade pyinstaller rarfile py7zr

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --icon "Src/Icon/VAE.ico" --name "VAE" --clean --optimize "2" --version-file "version.txt" --add-data "Src/extract_addons.py;." --add-data "Src/extract_archives.py;." --add-data "Src/Bin;Bin/"  "Src/cli.py"

      - name: Move Bin and Remove Gmad And 7-zip Linux/macOS
        run: |
          Move-Item -Path 'dist\VAE\_internal\Bin' -Destination 'dist\VAE\Bin'
          Remove-Item -Path 'dist\VAE\Bin\Linux\fastgmad' -Force
          Remove-Item -Path 'dist\VAE\Bin\Darwin\fastgmad' -Force
          Remove-Item -Path 'dist\VAE\Bin\Linux\7zz' -Force
          Remove-Item -Path 'dist\VAE\Bin\Darwin\7zz' -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: VAE-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}-Windows-x64
          path: dist/VAE
