name: Build macOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.18'
          architecture: 'x64'
          cache: 'pip'

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade pyinstaller rarfile py7zr

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "VAE" --strip --clean --optimize "2" --add-data "Src/extract_addons.py:." --add-data "Src/extract_archives.py:." --add-data "Src/Bin:Bin/"  "Src/cli.py"

      - name: Move Bin and Remove Gmad And 7zip Windows/Linux
        run: |
          mv dist/VAE/_internal/Bin dist/VAE/Bin
          rm -r dist/VAE/Bin/Windows/fastgmad.exe
          rm -f dist/VAE/Bin/Windows/7za.exe
          rm -f dist/VAE/Bin/Windows/7za.dll
          rm -f dist/VAE/Bin/Windows/7zxa.dll
          rm -f dist/VAE/Bin/Linux/fastgmad
          rm -f dist/VAE/Bin/Linux/7za

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VAE-2.x.x-macOS-x64
          path: dist/VAE
