name: Build Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'
          architecture: 'x64'

      - name: Create virtual environment
        run: py -m venv .venv

      - name: Activate virtual environment
        run: .venv\Scripts\activate

      - name: Install dependencies
        run: pip install pyinstaller rarfile py7zr

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --icon "Src/Icon/VAE.ico" --name "VAE" --clean --optimize "2" --version-file "version.txt" --add-data "Src/extract_addons.py;." --add-data "Src/extract_archives.py;." --add-data "Src/Bin;Bin/"  "Src/cli.py"

      - name: Move Bin and Remove Gmad Linux/macOS
        shell: bash
        run: |
          mv dist/VAE/_internal/Bin dist/VAE/
          rm dist/VAE/_internal/Bin/Linux/gmad_linux
          rm dist/VAE/_internal/Bin/macOS/gmad_osx

      - name: Set build date
        id: build_date
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VAE-Build-${{ steps.build_date.outputs.timestamp }}
          path: dist/VAE
