name: Build Ubuntu

on:
  push:
    branches:
      - beta
    paths:
      - '.github/workflows/**'
      - 'Src/**'
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10.15'
          architecture: 'x64'
          cache: 'pip'

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.3
        with:
          length: 7

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install dependencies
        run: pip install --upgrade pyinstaller rarfile py7zr

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "VAE" --strip --clean --optimize "2" --add-data "Src/extract_addons.py:." --add-data "Src/extract_archives.py:." --add-data "Src/Bin:Bin/"  "Src/cli.py"

      - name: Move Bin and Remove Gmad And 7-zip Windows/macOS
        run: |
          mv dist/VAE/_internal/Bin dist/VAE/Bin
          rm -f dist/VAE/Bin/Windows/fastgmad.exe
          rm -f dist/VAE/Bin/Windows/7zz.exe
          rm -f dist/VAE/Bin/Darwin/fastgmad
          rm -f dist/VAE/Bin/Darwin/7zz

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: VAE-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}-Linux-x64
          path: dist/VAE
